# Generated by Django 3.2.6 on 2021-08-27 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20210827_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='songs.artist')),
            ],
        ),
    ]
