# Generated by Django 3.2.5 on 2021-08-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='formed_in',
            field=models.IntegerField(default=2021),
        ),
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.CharField(default='Active', max_length=255),
        ),
    ]
